<?php
declare(strict_types=1);

/**
 * Escapers
 *
 * @author    Guido Scialfa <dev@guidoscialfa.com>
 * @copyright Copyright (c) 2018, Guido Scialfa
 * @license   GNU General Public License, version 2
 *
 * Copyright (C) 2018 Guido Scialfa <dev@guidoscialfa.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

return [
    'esc_html'     => 'esc_html',
    'esc_html__'   => 'esc_html__',
    'esc_html_e'   => 'esc_html_e',
    'esc_attr'     => 'esc_attr',
    'esc_attr__'   => 'esc_attr__',
    'esc_attr_e'   => 'esc_attr_e',
    'esc_js'       => 'esc_js',
    'esc_sql'      => 'esc_sql',
    'esc_textarea' => 'esc_textarea',
    'esc_url'      => 'esc_url',
    'esc_url_raw'  => 'esc_url_raw',
];
