<?php
/**
 * This file is part of the Twig WordPress package.
 *
 * (c) Guido Scialfa <dev@guidoscialfa.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

return [
    'esc_html' => 'esc_html',
    'esc_html__' => 'esc_html__',
    'esc_html_e' => 'esc_html_e',
    'esc_html_x' => 'esc_html_x',
    'esc_attr' => 'esc_attr',
    'esc_attr__' => 'esc_attr__',
    'esc_attr_e' => 'esc_attr_e',
    'esc_attr_x' => 'esc_attr_x',
    'esc_js' => 'esc_js',
    'esc_sql' => 'esc_sql',
    'esc_textarea' => 'esc_textarea',
    'esc_url' => 'esc_url',
    'esc_url_raw' => 'esc_url_raw',
];
