<?php
/**
 * This file is part of the Twig WordPress package.
 *
 * (c) Guido Scialfa <dev@guidoscialfa.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

return [
    'wp_kses' => 'wp_kses',
    'wp_kses_post' => 'wp_kses_post',
    'wp_kses_allowed_html' => 'wp_kses_allowed_html',
];
