<?php
/**
 * This file is part of the Twig WordPress package.
 *
 * (c) Guido Scialfa <dev@guidoscialfa.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

return [
    '__' => '__',
    '_e' => '_e',
    '_n' => '_n',
    '_x' => '_x',
    '_ex' => '_ex',
    '_nx' => '_nx',
    'esc_html__' => 'esc_html__',
    'esc_html_e' => 'esc_html_e',
    'esc_html_x' => 'esc_html_x',
    'esc_attr__' => 'esc_attr__',
    'esc_attr_e' => 'esc_attr_e',
    'esc_attr_x' => 'esc_attr_x',
];
